### ISSUE TITLE
Resolução desafio

### ISSUE THREAD

**Issue by vitoravale** [DevMasterTeam/desafio-festa-fim-de-ano#1]
Em MainActivity:63 não foi chamado o método responsável por iniciar a activity definida no intent que levaria o usuário para a tela do formulário de resposta. Alterar Para:
```java
if (id == R.id.button_confirm) {
    (...)
    startActivity(intent);
}
```
Em MainActivity:78 a chave a ser utilizada para a recuperação do estado da resposta do usuário está diferente da chave utilizada no armazenamento da informação. Alterar para:
```java
private void verifyPresence() {
    String presence = this.mSecurityPrefences.getStoredString(FimDeAnoConstants.PRESENCE);
    (...)
}
```
Para evitar maiores problemas e garantir um ponto único de definição da chave, é recomendado alterar os seguintes pontos para o que está sendo apresentado:
- MainActivity:62 => intent.putExtra(FimDeAnoConstants.PRESENCE", presence);
- DetailsActivity:40 => this.mSecurityPrefences.storeString(FimDeAnoConstants.PRESENCE, FimDeAnoConstants.CONFIRMED_WILL_GO);
- DetailsActivity:42 => this.mSecurityPrefences.storeString(FimDeAnoConstants.PRESENCE, FimDeAnoConstants.CONFIRMED_WONT_GO);
- DetailsActivity:50 => String presence = extras.getString(FimDeAnoConstants.PRESENCE);

**Comment by DevMasterTeam** [comment]
Fala Vitor! 
Sucesso demaaais! 

O que achou do desafio? Tranquilo? Seria legal ter mais desse tipo?
Um abraço e bons estudos!

**Comment by nathanraposo** [comment]
Olá muito bom andei dando uma olhada no código e existem esses erros apresentados.

vlw
