### ISSUE TITLE
Desafio - Erros encontrados e corrigidos

### ISSUE THREAD

**Issue by sudorafa** [DevMasterTeam/desafio-festa-fim-de-ano#2]
Na linha 62 - Não passa a key para o FimDeAnoConstants corretamente quando onClick
No desafio: `intent.putExtra("presence_key", presence);`
Certo para passar: `intent.putExtra(FimDeAnoConstants.PRESENCE, presence);` 

E ainda não chamou a activity:
`startActivity(intent);`

Na linha 77 - Não passa o valor da constante por parâmetro de FimDeAnoConstants, com isso quando volta não exibe na activity main conforme marcou no check.
No desafio: `String presence = this.mSecurityPrefences.getStoredString("presence_Key");`
Certo para passar: `String presence = this.mSecurityPrefences.getStoredString(FimDeAnoConstants.PRESENCE);`

**Comment by DevMasterTeam** [comment]
Shooow de bola! Imagino que funcionou legal depois das alterações?

O que achou de desafios desse tipo? É uma boa?
Abraço e bons estudos!
